### ISSUE TITLE
setup.sh file not found

### ISSUE THREAD

**Issue by migueldvb** [lsst/lsst#14]
newinstall.sh gives the error shown below when it installs the default EUPS v1.5.9:
```
Using python at /usr/bin/python2 to install EUPS
Installing EUPS (v1.5.9)...  done.
../lsst/scripts/newinstall.sh: line 296: /home/mdevalbo/project/LSST/newinstall_stack/eups/bin/setups.sh: No such file or directory
Installing the basic environment ... 
../lsst/scripts/newinstall.sh: line 321: eups: command not found
```
However when the latest EUPS revision is selected this error does not occur.

**Comment by timj** [comment]
That's weird. #15 has presumably fixed it then (updating to 2.0.1) but it's strange that it no-one else got the problem. It looks like EUPS had not been installed properly.

**Comment by jhoblitt** [comment]
@migueldvb Could you try renaming your `~/.eups` directory and re-running `newinstall.sh`?

**Comment by migueldvb** [comment]
Since then I have upgraded to v2.0.1 and I do not get this error any more. It was likely some problem with my installation and the issue is no longer relevant so this can be closed.
